#!/usr/bin/env -S pnpm tsx
/**
 * check-mcp-catalogs — sanity checks for every `mcp/*.json` catalog
 * (`schema: "context-mcp-catalog/1"`). These files are generated by each MCP
 * server repo's own `export-mcp-catalog` script from its real tool registry
 * and committed here verbatim — see mcp/README.md. This script never edits
 * them, it only validates what is already committed:
 *
 *   - valid JSON, top-level `schema` is exactly "context-mcp-catalog/1"
 *   - `server.key` equals the filename (mcp/<key>.json)
 *   - `server.endpoint` is an https:// URL
 *   - every tool name (across all `toolGroups[].tools[]`) is unique
 *   - `counts.total` equals the number of tools
 *   - `counts.shared + counts.paired == counts.total`
 *   - every tool has a non-empty name, title and description
 *
 * Exit 1 with one line per problem. No database, no network.
 *
 *   pnpm check-mcp-catalogs
 */
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const MCP_CATALOG_SCHEMA = "context-mcp-catalog/1";

export type McpTool = { name?: string; title?: string; description?: string };
export type McpToolGroup = { tools?: McpTool[] };
export type McpCatalog = {
  schema?: string;
  server?: { key?: string; name?: string; endpoint?: string; contractVersion?: string };
  toolGroups?: McpToolGroup[];
  counts?: { total?: number; shared?: number; paired?: number };
};

/** Validate one parsed catalog against its expected filename key. Returns problem strings (empty = OK). */
export function validateCatalog(file: string, key: string, catalog: McpCatalog): string[] {
  const problems: string[] = [];
  if (catalog.schema !== MCP_CATALOG_SCHEMA) {
    problems.push(`${file}: schema "${catalog.schema}" must be "${MCP_CATALOG_SCHEMA}"`);
  }
  if (!catalog.server?.key) problems.push(`${file}: server.key is missing`);
  else if (catalog.server.key !== key) problems.push(`${file}: server.key "${catalog.server.key}" must equal filename key "${key}"`);
  if (!catalog.server?.name) problems.push(`${file}: server.name is missing`);
  if (!catalog.server?.contractVersion) problems.push(`${file}: server.contractVersion is missing`);
  if (!catalog.server?.endpoint) problems.push(`${file}: server.endpoint is missing`);
  else if (!/^https:\/\//.test(catalog.server.endpoint)) problems.push(`${file}: server.endpoint "${catalog.server.endpoint}" must be an https:// URL`);

  const groups = catalog.toolGroups ?? [];
  const tools = groups.flatMap((g) => g.tools ?? []);
  const seen = new Set<string>();
  for (const t of tools) {
    if (!t.name) problems.push(`${file}: a tool is missing a name`);
    else if (seen.has(t.name)) problems.push(`${file}: duplicate tool name "${t.name}"`);
    else seen.add(t.name);
    if (!t.title) problems.push(`${file}: tool "${t.name ?? "?"}" is missing a title`);
    if (!t.description || !t.description.trim()) problems.push(`${file}: tool "${t.name ?? "?"}" is missing a description`);
  }

  const total = catalog.counts?.total;
  if (total === undefined) problems.push(`${file}: counts.total is missing`);
  else if (total !== tools.length) problems.push(`${file}: counts.total (${total}) must equal the number of tools (${tools.length})`);

  const shared = catalog.counts?.shared;
  const paired = catalog.counts?.paired;
  if (shared === undefined) problems.push(`${file}: counts.shared is missing`);
  if (paired === undefined) problems.push(`${file}: counts.paired is missing`);
  if (shared !== undefined && paired !== undefined && total !== undefined && shared + paired !== total) {
    problems.push(`${file}: counts.shared (${shared}) + counts.paired (${paired}) must equal counts.total (${total})`);
  }

  return problems;
}

function main() {
  const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
  const MCP_DIR = join(ROOT, "mcp");
  const problems: string[] = [];

  if (!existsSync(MCP_DIR)) {
    console.log("check-mcp-catalogs: no mcp/ directory, nothing to check");
    return;
  }

  const files = readdirSync(MCP_DIR).filter((f) => f.endsWith(".json")).sort();
  let checked = 0;
  for (const f of files) {
    const abs = join(MCP_DIR, f);
    const key = basename(f, ".json");
    const raw = readFileSync(abs, "utf8");
    let catalog: McpCatalog;
    try {
      catalog = JSON.parse(raw);
    } catch (e) {
      problems.push(`mcp/${f}: invalid JSON (${(e as Error).message})`);
      continue;
    }
    if (catalog.schema !== MCP_CATALOG_SCHEMA) continue; // not an MCP catalog — skip silently
    checked++;
    problems.push(...validateCatalog(`mcp/${f}`, key, catalog));
  }

  if (problems.length > 0) {
    for (const p of problems) console.error(p);
    process.exit(1);
  }
  console.log(`check-mcp-catalogs: ${checked} catalog(s) OK`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
